spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    generate-unique-name: false
    name: testdb
#    url: jdbc:h2:file:/data/demo
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#logging:
#  level:
#    org:
#      springframework: DEBUG